src/Entity/Gift.php
<?php

namespace App\Entity;

use App\Repository\GiftRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GiftRepository::class)
 */
class Gift
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $designation;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $minimum_age;

    /**
     * @ORM\Column(type="float")
     */
    private $average_price;

    /**
     * @ORM\ManyToMany(targetEntity=Personne::class, inversedBy="personnes")
     *
     */
    private $personnes;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="gifts")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id") //reference of the column targetted here
     */
    private $category;

    public function __construct()
    {
        $this->personnes = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(?string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function getMinimumAge(): ?int
    {
        return $this->minimum_age;
    }

    public function setMinimumAge(?int $minimum_age): self
    {
        $this->minimum_age = $minimum_age;

        return $this;
    }

    public function getAveragePrice(): ?float
    {
        return $this->average_price;
    }

    public function setAveragePrice(float $average_price): self
    {
        $this->average_price = $average_price;

        return $this;
    }

    /**
     * @return Collection|Personne[]
     */
    public function getPersonnes(): Collection
    {
        return $this->personnes;
    }

    public function addPersonne(Personne $personne): self
    {
        if (!$this->personnes->contains($personne)) {
            $this->personnes[] = $personne;
        }

        return $this;
    }

    public function removePersonne(Personne $personne): self
    {
        $this->personnes->removeElement($personne);

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function parity(): float
    {
        $peoples = $this->getPersonnes();
        $numberOfWomen = 0;

        foreach ($peoples as $people) {
            if ($people->getSex() == 'female') {
                $numberOfWomen++;
            }
        }

        if ($numberOfWomen === 0) {
            return 0;
        }

        $total = $this->getTotalPeoples();
        return ($numberOfWomen * 100 / $total);
    }

    public function getTotalPeoples(): int
    {
        $peoples = $this->getPersonnes();
        $total = count($peoples->getValues());

        return $total;
    }

    /**
     * @return Collection|Personne[]
     */
    public function getAgeInappropriatePeoples(): ?Collection
    {
        $peoples = $this->getPersonnes();
        $ageMax = $this->getMinimumAge();

        $less = new ArrayCollection();
        foreach ($peoples as $people) {
            if ($people->age() < $ageMax) {
                $less->add($people);
            }
        }

        return $less;
    }

    public function ageIsInRange(int $min, int $max): bool
    {
        foreach ($this->personnes as $personne) {
            $age = $personne->age();
            if ($age > $min && $age < $max) {
                return true;
            }
        }

        return false;
    }
}

src/Form/GiftType.php
<?php

namespace App\Form;

use App\Entity\Gift;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GiftType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('designation', null, [
                'attr' => [
                    'disabled' => $options['e']
                ]
            ])
            ->add('minimum_age')
            ->add('average_price')
            ->add('category', CategoryType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Gift::class,
            'e' => false
        ]);
    }
}

src/Controller/GiftController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Gift;
use App\Entity\Personne;
use App\Form\GiftType;
use App\Repository\GiftRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/gift")
 * @IsGranted("ROLE_GESTION")
 */
class GiftController extends AbstractController
{
    /**
     * @Route("/", name="gift_index", methods={"GET"})
     */
    public function index(GiftRepository $giftRepository): Response
    {
        return $this->render('gift/index.html.twig', [
            'gifts' => $giftRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="gift_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $gift = new Gift();
        $form = $this->createForm(GiftType::class, $gift);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $repo = $this->getDoctrine()->getManager()->getRepository(Category::class);

            $category = $repo->findIfExist($gift->getCategory());

            if (count($category)) {
                $gift->setCategory($category[0]);
            } else {
                $entityManager->persist($gift->getCategory());
                $entityManager->flush();
            }
            $entityManager->persist($gift);
            $entityManager->flush();

            return $this->redirectToRoute('gift_index');
        }

        return $this->render('gift/new.html.twig', [
            'gift' => $gift,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="gift_show", methods={"GET"})
     */
    public function show(Gift $gift): Response
    {
        return $this->render('gift/show.html.twig', [
            'gift' => $gift,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="gift_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Gift $gift): Response
    {
        $designtion = $this->getDoctrine()->getRepository(Gift::class)->find($gift->getId())->getDesignation();
        $form = $this->createForm(GiftType::class, $gift, ['e' => true]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $gift->setDesignation($designtion);
            $entityManager->persist($gift);
            $entityManager->flush();

            return $this->redirectToRoute('gift_index');
        }

        return $this->render('gift/edit.html.twig', [
            'gift' => $gift,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="gift_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Gift $gift): Response
    {
        if ($this->isCsrfTokenValid('delete' . $gift->getId(), $request->request->get('_token')) && count($gift->getPersonnes()) === 0) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($gift);
            $entityManager->flush();
        }

        return $this->redirectToRoute('gift_index');
    }

    /**
     * @Route("/list_age_inappropriate/{id}", name="gift_list_age_inap", methods={"GET"})
     */
    public function listOfAgeInappropriatePeoples(Request $request, Gift $gift)
    {
        $less = $gift->getAgeInappropriatePeoples();

        if (!$less) {
            return $this->render('personne/index.html.twig', [
                'personnes' => null,
                'message' => 'Toutes les personne on le bon age !!'
            ]);
        }

        return $this->render('personne/index.html.twig', [
            'personnes' => $less,
            'message' => 'La ou les personnes suivantes sont trop jeune'
        ]);
    }
}

templates/gift/_delete_form.html.twig
<form method="post" action="{{ path('gift_delete', {'id': gift.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ gift.id) }}">
    <button class="btn"
            {% if (gift.personnes.count!= 0) %}
                onclick="return false;"
                style="color: red"
                title="Impossible to delete this gift, someone still has it on his wish list"
            {% endif %}
    >Delete</button>
</form>

templates/gift/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/gift/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Gift{% endblock %}

{% block body %}
    <h1>Edit Gift</h1>

    {{ include('gift/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('gift_index') }}">back to list</a>

    {{ include('gift/_delete_form.html.twig') }}
{% endblock %}

templates/gift/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gift index{% endblock %}

{% block body %}
    <h1>Gift index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Designation</th>
                <th>Minimum_age</th>
                <th>Average_price</th>
                <th>Category</th>
                <th>Actions</th>
                <th>Parity (percentage of women)</th>
                <th>list of age-inappropriate persons</th>
            </tr>
        </thead>
        <tbody>
        {% for gift in gifts %}
            <tr>
                <td>{{ gift.id }}</td>
                <td>{{ gift.description }}</td>
                <td>{{ gift.designation }}</td>
                <td>{{ gift.minimumAge }}</td>
                <td>{{ gift.averagePrice }}</td>
                <td>{{ gift.category.name }}</td>
                <td>
                    <a href="{{ path('gift_show', {'id': gift.id}) }}">Show</a>
                    <a href="{{ path('gift_edit', {'id': gift.id}) }}">Edit</a>
                    {{ include('gift/_delete_form.html.twig') }}
                </td>
                <td>{{ gift.parity() }}% on {{ gift.getTotalPeoples() }} people(s)</td>
                <td><a href="{{ path('gift_list_age_inap', {'id': gift.id}) }}">List</a></td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('gift_new') }}">Create new</a>
{% endblock %}

templates/gift/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Gift{% endblock %}

{% block body %}
    <h1>Create new Gift</h1>

    {{ include('gift/_form.html.twig') }}

    <a href="{{ path('gift_index') }}">back to list</a>
{% endblock %}

templates/gift/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gift{% endblock %}

{% block body %}
    <h1>Gift</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ gift.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ gift.description }}</td>
            </tr>
            <tr>
                <th>Designation</th>
                <td>{{ gift.designation }}</td>
            </tr>
            <tr>
                <th>Minimum_age</th>
                <td>{{ gift.minimumAge }}</td>
            </tr>
            <tr>
                <th>Average_price</th>
                <td>{{ gift.averagePrice }}</td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ gift.category.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('gift_index') }}">back to list</a>

    <a href="{{ path('gift_edit', {'id': gift.id}) }}">edit</a>

    {{ include('gift/_delete_form.html.twig') }}
{% endblock %}