src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @UniqueEntity(
 *     fields={"number","street", "zip_code", "city"},
 *     message="cette adresse est déjà renseigné."
 * )
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 */
class Address
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity=Personne::class, mappedBy="fk_address")
     */
    private $personnes;

    public function __construct()
    {
        $this->personnes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|null
     */
    public function getPersonnes(): ?Collection
    {
        return $this->personnes;
    }

    public function addPersonne(Personne $personne): self
    {
        if (!$this->personnes->contains($personne)) {
            $this->personnes[] = $personne;
            $personne->setAddress($this);
        }

        return $this;
    }

    public function removePersonne(Personne $personne): self
    {
        if ($this->personnes->removeElement($personne)) {
            if ($personne->getAddress() === $this) {
                $personne->setAddress(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->number . ' ' . $this->street . ' ' . $this->zip_code . ' ' . $this->city;
    }
}

src/Entity/Personne.php
<?php

namespace App\Entity;

use App\Repository\PersonneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @UniqueEntity(
 *     fields={"name_surname"},
 *     message="cette utilisateur est déjà enregistré."
 * )
 * @ORM\Entity(repositoryClass=PersonneRepository::class)
 */
class Personne
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $name_surname;

    /**
     * @ORM\Column(type="string", length=255, columnDefinition="ENUM('male', 'female', 'not indicated')")
     */
    private $sex;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_of_birth;

    /**
     * @ORM\ManyToOne(targetEntity=Address::class, inversedBy="personnes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fk_address;


    /**
     * @ORM\ManyToMany(targetEntity=Gift::class, mappedBy="personnes")
     */
    private $gifts;

    public function __construct()
    {
        $this->gifts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameSurname(): ?string
    {
        return $this->name_surname;
    }

    public function setNameSurname(?string $name_surname): self
    {
        $this->name_surname = $name_surname;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTime
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(?\DateTime $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->fk_address;
    }

    public function setAddress(?Address $address): self
    {
        $this->fk_address = $address;

        return $this;
    }

    public function getFkAddress(): ?Address
    {
        return $this->fk_address;
    }

    public function setFkAddress(?Address $fk_address): self
    {
        $this->fk_address = $fk_address;

        return $this;
    }

    /**
     * @return Collection|Gift[]
     */
    public function getGifts(): Collection
    {
        return $this->gifts;
    }

    public function addGift(Gift $gift): self
    {
        if (!$this->gifts->contains($gift)) {
            $this->gifts[] = $gift;
            $gift->addPersonne($this);
        }

        return $this;
    }

    public function removeGift(Gift $gift): self
    {
        if ($this->gifts->removeElement($gift)) {
            $gift->removePersonne($this);
        }

        return $this;
    }

    function age(): string
    {
        $birthDate = $this->getDateOfBirth()->format("Y-m-d");
        $today = date("Y-m-d");
        $diff = date_diff(date_create($birthDate), date_create($today));
        return $diff->format('%y');
    }
}

src/Form/PersonneType.php
<?php

namespace App\Form;

use App\Entity\Personne;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PersonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_surname', TextType::class, [
                'attr' => [
                    'disabled' => $options['e']
                ]
            ])
            ->add('sex', ChoiceType::class, array(
                'choices' => array('Male' => 'male', 'Female' => 'female', 'i don\'t want indicate it' => 'not indicated'),
            ))
            ->add('date_of_birth', BirthdayType::class)
            ->add('address', AddressType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Personne::class,
            'e' => false
        ]);
    }
}

src/Controller/PersonneController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Entity\Gift;
use App\Entity\Personne;
use App\Form\PersonneType;
use App\Repository\AddressRepository;
use App\Repository\PersonneRepository;
use Doctrine\Persistence\ManagerRegistry;
use mysql_xdevapi\CrudOperationBindable;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/personne")
 */
class PersonneController extends AbstractController
{
    /**
     * @Route("/", name="personne_index", methods={"GET"})
     */
    public function index(PersonneRepository $personneRepository): Response
    {
        return $this->render('personne/index.html.twig', [
            'personnes' => $personneRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="personne_new", methods={"GET","POST"})
     * @IsGranted("ROLE_SECRETARIAT")
     */
    public function new(Request $request): Response
    {
        $personne = new Personne();
        $form = $this->createForm(PersonneType::class, $personne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $repo = $this->getDoctrine()->getManager()->getRepository(Address::class);

            $address = $repo->findIfExist($personne->getAddress());

            if (count($address)) {
                $personne->setAddress($address[0]);
            } else {
                $entityManager->persist($personne->getAddress());
                $entityManager->flush();
            }

            $entityManager->persist($personne);
            $entityManager->flush();

            return $this->redirectToRoute('personne_index');
        }

        return $this->render('personne/new.html.twig', [
            'personne' => $personne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="personne_show", methods={"GET"})
     */
    public function show(Personne $personne): Response
    {
        return $this->render('personne/show.html.twig', [
            'personne' => $personne,
            'address' => $personne->getAddress()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="personne_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_SECRETARIAT")
     */
    public function edit(Request $request, Personne $personne): Response
    {
        $personneName = $this->getDoctrine()->getRepository(Personne::class)->find($personne->getId())->getNameSurname();
        $form = $this->createForm(PersonneType::class, $personne, ['e' => true]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $personne->setNameSurname($personneName);
            $entityManager->persist($personne);
            $entityManager->flush();

            return $this->redirectToRoute('personne_index');
        }

        return $this->render('personne/edit.html.twig', [
            'personne' => $personne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="personne_delete", methods={"DELETE"})
     * @IsGranted("ROLE_SECRETARIAT")
     */
    public function delete(Request $request, Personne $personne): Response
    {
        if ($this->isCsrfTokenValid('delete' . $personne->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($personne);
            $entityManager->flush();
        }

        return $this->redirectToRoute('personne_index');
    }

    /**
     * @Route("/search", name="personne_search", methods={"POST"})
     * @param Request $request
     * @return Response
     */
    public function searchAction(Request $request): Response
    {
        $street = $request->request->get('search_street');
        $zipCode = $request->request->get('search_zip_code');


        if (empty($street) || empty($zipCode)) {
            return $this->redirectToRoute('personne_index');
        }
        $repoAddress = $this->getDoctrine()->getManager()->getRepository(Address::class);
        $addresses = $repoAddress->findByStreetAndCity($street, $zipCode);


        foreach ($addresses as $address) {
            $personnes = $address->getPersonnes();
        }

        return $this->render('personne/index.html.twig', [
            'personnes' => $personnes,
        ]);
    }

    /**
     * @Route("/list/{id}", name="personne_wish_list", methods={"GET"})
     */
    public function wishList(Request $request, Personne $personne): Response
    {
        return $this->render('personne/list.html.twig', [
            'personne' => $personne,
            'gifts' => $personne->getGifts()
        ]);
    }

    /**
     * @Route("/list/add/{id}", name="_add", methods={"POST"})
     * @param Request $request
     * @return Response
     */
    public function addGiftToTheWishList(Request $request, Personne $personne): Response
    {
        // ToDo implementation
        $giftName = $request->request->get('add');

        $giftToAdd = $this->getDoctrine()->getRepository(Gift::class)->findByDesignation($giftName);

        if (count($giftToAdd) === 0) {
            return $this->render('personne/list.html.twig', [
                'personne' => $personne,
                'gifts' => $personne->getGifts(),
                'message' => 'This gift is not found'
            ]);
        }

        if ($personne->getGifts()->contains($giftToAdd[0])) {
            return $this->render('personne/list.html.twig', [
                'personne' => $personne,
                'gifts' => $personne->getGifts(),
                'message' => 'This gift is already added'
            ]);
        }

        $personne->addGift($giftToAdd[0]);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($personne);
        $entityManager->flush();


        return $this->render('personne/list.html.twig', [
            'personne' => $personne,
            'gifts' => $personne->getGifts()
        ]);
    }

    /**
     * @Route("/list/remove/{id_personne}/{id_gift}", name="_delete_gift", methods={"POST"})
     * @ParamConverter("personne", options={"mapping": {"id_personne"   : "id"}})
     * @ParamConverter("gift", options={"mapping": {"id_gift"   : "id"}})
     * @param Request $request
     * @return Response
     */
    public function removeGiftToTheWishList(Request $request, Personne $personne, Gift $gift): Response
    {
        $personne->removeGift($gift);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($personne);
        $entityManager->flush();


        return $this->render('personne/list.html.twig', [
            'personne' => $personne,
            'gifts' => $personne->getGifts()
        ]);
    }
}

templates/personne/_delete_form.html.twig
<form method="post" action="{{ path('personne_delete', {'id': personne.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personne.id) }}">
    <button class="btn">Delete</button>
</form>

templates/personne/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/personne/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Personne{% endblock %}

{% block body %}
    <h1>Edit Personne</h1>

    {{ include('personne/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('personne_index') }}">back to list</a>

    {{ include('personne/_delete_form.html.twig') }}
{% endblock %}

templates/personne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personne index{% endblock %}

{% block body %}
    <h1>Personne index</h1>

    <form class="pull-right hidden" role="search" id="nav-search-form" method="post" action="{{ path('personne_search') }}">
        <thead>
            <tr>
                <th>Search by street and zip-code</th>
            </tr>
        </thead>
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Boulevard de Dury*" name ="search_street" required>
            <input type="text" class="form-control" placeholder="80000*" name ="search_zip_code" required>
            <button type="submit" class="btn">Search</button>
        </div>
        <span>
                fields marked with * are mandatory
            </span>
    </form>

    <form action={{ path('personne_index') }}>
        <input type="submit" value="Reset" />
    </form>

    {% if message is defined %}
        <h2 style="color: red">{{ message }}</h2>
    {% endif %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name Surname</th>
                <th>Gender</th>
                <th>Date of Birth</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for personne in personnes %}
            <tr>
                <td>{{ personne.id }}</td>
                <td>{{ personne.nameSurname }}</td>
                <td>{{ personne.sex }}</td>
                <td>{{ personne.dateOfBirth ? personne.dateOfBirth|date('Y-m-d') : '' }}</td>
                <td>

                    <a href="{{ path('personne_show', {'id': personne.id}) }}">show</a>
                    <a href="{{ path('personne_wish_list', {'id': personne.id}) }}">wish List</a>
                    {% if app.user.roles is defined %}
                        {% if "ROLE_SECRETARIAT" in app.user.roles %}
                            <a href="{{ path('personne_edit', {'id': personne.id}) }}">edit</a>
                            {{ include('personne/_delete_form.html.twig') }}
                        {% endif %}
                    {% endif %}

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if app.user.roles is defined %}
        {% if "ROLE_SECRETARIAT" in app.user.roles %}
            <a href="{{ path('personne_new') }}">Create new</a>
        {% endif %}
    {% endif %}
{% endblock %}

templates/personne/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personne{% endblock %}

{% block body %}
    <h1>Personne</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ personne.id }}</td>
        </tr>
        <tr>
            <th>Name_surname</th>
            <td>{{ personne.nameSurname }}</td>
        </tr>
    </table>
    <br>
    <br>

    <h1>Wish List</h1>

    Add gift to the wish list :
    {% if message is defined %}
        <h3 style="color: red">{{ message }}</h3>
    {% endif %}
    <form class="pull-right hidden" role="search" id="nav-search-form" method="post" action="{{ path('_add', {'id': personne.id}) }}">
        <div class="input-group">
            <label>
                <input type="text" class="form-control" placeholder="Monopoly" name ="add" required="required">
            </label>
            <button type="submit" class="btn">add</button>
        </div>
    </form>
    <br>
    <br>

    {% for gift in gifts %}
        <li>
            <td>{{ gift.designation }}</td>
                <a href="{{ path('gift_show', {'id': gift.id}) }}">show</a>
                <form class="pull-right hidden" role="search" id="nav-search-form" method="post" action="{{ path('_delete_gift', {'id_gift': gift.id, 'id_personne': personne.id }) }}">
                        <button type="submit" class="btn">remove</button>
                </form>
        </li>
        <br>
    {% else %}
        <tr>
            <td colspan="6">no records found</td>
        </tr>
    {% endfor %}

    <br>
    <br>
    <br>

    <a href="{{ path('personne_index') }}">back to list</a>
{% endblock %}

templates/personne/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Personne{% endblock %}

{% block body %}
    <h1>Create new Personne</h1>

    {{ include('personne/_form.html.twig') }}

    <a href="{{ path('personne_index') }}">back to list</a>
{% endblock %}

templates/personne/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personne{% endblock %}

{% block body %}
    <h1>Personne</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ personne.id }}</td>
            </tr>
            <tr>
                <th>Name_surname</th>
                <td>{{ personne.nameSurname }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ personne.sex }}</td>
            </tr>
            <tr>
                <th>Date_of_birth</th>
                <td>{{ personne.dateOfBirth ? personne.dateOfBirth|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>
    <br>

    <h1>Address</h1>
    <table>
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ address.id }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ address.city }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ address.number }}</td>
            </tr>
            <tr>
                <th>Zip Code</th>
                <td>{{ address.zipCode }}</td>
            </tr>
            <tr>
                <th>Street</th>
                <td>{{ address.street }}</td>
            </tr>
        </tbody>
    </table>

    <br>

    <a href="{{ path('personne_index') }}">back to list</a>

    {% if app.user.roles is defined %}
        {% if "ROLE_SECRETARIAT" in app.user.roles %}
            <a href="{{ path('personne_edit', {'id': personne.id}) }}">edit</a>
            {{ include('personne/_delete_form.html.twig') }}
        {% endif %}
    {% endif %}

{% endblock %}