src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @UniqueEntity(
 *     fields={"number","street", "zip_code", "city"},
 *     message="cette adresse est déjà renseigné."
 * )
 * @ORM\Entity(repositoryClass=AddressRepository::class)
 */
class Address
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity=Personne::class, mappedBy="fk_address")
     */
    private $personnes;

    public function __construct()
    {
        $this->personnes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|null
     */
    public function getPersonnes(): ?Collection
    {
        return $this->personnes;
    }

    public function addPersonne(Personne $personne): self
    {
        if (!$this->personnes->contains($personne)) {
            $this->personnes[] = $personne;
            $personne->setAddress($this);
        }

        return $this;
    }

    public function removePersonne(Personne $personne): self
    {
        if ($this->personnes->removeElement($personne)) {
            if ($personne->getAddress() === $this) {
                $personne->setAddress(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->number . ' ' . $this->street . ' ' . $this->zip_code . ' ' . $this->city;
    }
}

src/Form/AddressType.php
<?php

namespace App\Form;

use App\Entity\Address;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('street')
            ->add('number')
            ->add('zip_code')
            ->add('city');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Address::class,
        ]);
    }
}

src/Controller/AddressController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Form\AddressType;
use App\Repository\AddressRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/address")
 * @IsGranted("ROLE_SECRETARIAT")
 */
class AddressController extends AbstractController
{
    /**
     * @Route("/", name="address_index", methods={"GET"})
     * @param AddressRepository $addressRepository
     * @return Response
     */
    public function index(AddressRepository $addressRepository): Response
    {
        return $this->render('address/index.html.twig', [
            'addresses' => $addressRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="address_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $address = new Address();
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($address);
            $entityManager->flush();

            return $this->redirectToRoute('address_index');
        }

        return $this->render('address/new.html.twig', [
            'address' => $address,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="address_show", methods={"GET"})
     * @param Address $address
     * @return Response
     */
    public function show(Address $address): Response
    {
        return $this->render('address/show.html.twig', [
            'address' => $address,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="address_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Address $address
     * @return Response
     */
    public function edit(Request $request, Address $address): Response
    {
        $form = $this->createForm(AddressType::class, $address);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('address_index');
        }

        return $this->render('address/edit.html.twig', [
            'address' => $address,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="address_delete", methods={"DELETE"})
     * @param Request $request
     * @param Address $address
     * @return Response
     */
    public function delete(Request $request, Address $address): Response
    {

        if ($this->isCsrfTokenValid('delete' . $address->getId(), $request->request->get('_token')) && count($address->getPersonnes()) === 0) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($address);
            $entityManager->flush();

            return $this->redirectToRoute('address_index');
        } else {
            return $this->redirectToRoute('address/index.html.twig');
        }

    }


    /**
     * @Route("/search", name="_search", methods={"POST"})
     * @param Request $request
     * @return Response
     */
    public function searchAction(Request $request): Response
    {
        $data = $request->request->get('search');

        if (empty($data)) {
            return $this->redirectToRoute('address_index');
        }

        $repo = $this->getDoctrine()->getManager()->getRepository(Address::class);

        return $this->render('address/index.html.twig', [
            'addresses' => $repo->findByCity($data),
        ]);
    }
}

templates/address/_delete_form.html.twig
<form method="post" action="{{ path('address_delete', {'id': address.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ address.id) }}">
    <button class="btn"
            {% if (address.personnes.count!= 0) %}
                onclick="return false;"
                style="color: red"
                title="Impossible to delete this address, someone is still living in it"
            {% endif %}
    >Delete</button>
</form>

templates/address/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/address/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Address{% endblock %}

{% block body %}
    <h1>Edit Address</h1>

    {{ include('address/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('address_index') }}">back to list</a>

    {{ include('address/_delete_form.html.twig') }}
{% endblock %}

templates/address/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Address index{% endblock %}

{% block body %}
    <h1>Address index</h1>

    <br>
    <h3>Search by city</h3>
    <form class="pull-right hidden" role="search" id="nav-search-form" method="post" action="{{ path('_search') }}">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Amiens" name ="search" required>
            <button type="submit" class="btn">Search</button>
        </div>
    </form>
    <br>
    <a href="{{ path('address_index') }}">reset</a>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Street</th>
                <th>Number</th>
                <th>Zip_code</th>
                <th>City</th>
                <th>number of inhabitants</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for address in addresses %}
            <tr>
                <td>{{ address.id }}</td>
                <td>{{ address.street }}</td>
                <td>{{ address.number }}</td>
                <td>{{ address.zipCode }}</td>
                <td>{{ address.city }}</td>
                <td>{{ address.personnes.count }}</td>
                <td>
                    <a href="{{ path('address_show', {'id': address.id}) }}">show</a>
                    <a href="{{ path('address_edit', {'id': address.id}) }}">edit</a>
                    {{ include('address/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('address_new') }}">Create new</a>

{% endblock %}

templates/address/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Address{% endblock %}

{% block body %}
    <h1>Create new Address</h1>

    {{ include('address/_form.html.twig') }}

    <a href="{{ path('address_index') }}">back to list</a>
{% endblock %}

templates/address/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Address{% endblock %}

{% block body %}
    <h1>Address</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ address.id }}</td>
            </tr>
            <tr>
                <th>Street</th>
                <td>{{ address.street }}</td>
            </tr>
            <tr>
                <th>Number</th>
                <td>{{ address.number }}</td>
            </tr>
            <tr>
                <th>Zip_code</th>
                <td>{{ address.zipCode }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ address.city }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('address_index') }}">back to list</a>

    <a href="{{ path('address_edit', {'id': address.id}) }}">edit</a>

    {{ include('address/_delete_form.html.twig') }}
{% endblock %}